package com.example.hellonobase;

import com.j256.ormlite.field.DatabaseField;

import java.io.Serializable;
import java.util.Date;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class HistoryVideo implements Serializable {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int id;
    @DatabaseField(index = true)
    public String video_id;
    @DatabaseField
    public String url;
    @DatabaseField
    public String published_at;
    @DatabaseField
    public String vcount;
    @DatabaseField
    public String shared_url;
    @DatabaseField
    public String title;
    @DatabaseField
    public String image_url;
    @DatabaseField
    public String description;
    @DatabaseField
    public Date date;

    // @DatabaseField
    // boolean even;

    public HistoryVideo() {
        // needed by ormlite
    }

    public HistoryVideo(long millis) {
        this.date = new Date(millis);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getVcount() {
        return vcount;
    }

    public void setVcount(String vcount) {
        this.vcount = vcount;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getShared_url() {
        return shared_url;
    }

    public void setShared_url(String shared_url) {
        this.shared_url = shared_url;
    }

    public String getVideo_id() {
        return video_id;
    }

    public void setVideo_id(String video_id) {
        this.video_id = video_id;
    }

    public String getPublished_at() {
        return published_at;
    }

    public void setPublished_at(String published_at) {
        this.published_at = published_at;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

}
